import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createApp} from '../server.js';
import {migrateFloor} from '../floor-domain.js';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {createHmac} from 'node:crypto';

test('branch checkout constraints and bilingual modifier prices are enforced on the server',async t=>{const {call,manager,read}=await setup(t);let m=read().menu[0];const metadata={id:m.id,version:m.version,nameAr:'طبق',description:'Dish',descriptionAr:'طبق',spice:0,prepMinutes:null,modifiers:[{id:'extra',name:'Extra',nameAr:'إضافة',price:1000,available:true,required:true}]};assert.equal((await call('menu-metadata',metadata)).status,401);assert.equal((await call('menu-metadata',metadata,manager)).status,200);assert.equal(read().menu[0].modifiers[0].nameAr,'إضافة');const order={branchId:'main',type:'pickup',name:'Guest',contact:'fictional',payment:'demo',lines:[{id:m.id,qty:1,options:[],price:m.price}],key:'required'};assert.equal((await call('online-order',order)).status,400);assert.equal((await call('online-order',{...order,key:'options',lines:[{id:m.id,qty:1,options:['extra'],price:m.price+1000}]})).status,200);assert.equal(read().payments[0].amount,m.price+1000);assert.equal((await call('branch',{id:'main',name:'Main',nameAr:'الرئيسي',active:true,pickup:false,delivery:true,deliveryAreas:['Local'],paymentProvider:'demo'},manager)).status,200);assert.equal((await call('online-order',{...order,key:'no-pickup'})).status,400);assert.equal((await call('online-order',{...order,type:'delivery',area:'Elsewhere',address:'Address',key:'bad-area'})).status,400);});

test('premium online checkout is menu-first, priced on server, atomic and retry-safe',async t=>{const {call,read}=await setup(t);const b={branchId:'main',type:'pickup',name:'Guest',contact:'fictional',payment:'demo',lines:[{id:'m0',qty:2,price:14500}],key:'online'};assert.equal((await call('online-order',b)).status,200);assert.equal((await call('online-order',b)).status,200);assert.equal(read().orders.length,1);assert.equal(read().payments[0].amount,29000);assert.equal(read().menu[0].stock,16);assert.equal((await call('online-order',{...b,key:'bad',lines:[{id:'m0',qty:1,price:1}]})).status,409);assert.equal(read().orders.length,1);assert.equal((await call('online-order',{...b,key:'area',type:'delivery',address:'fictional',area:'outside'})).status,400);assert.equal(read().visits.length,1);});
test('split invitation scopes, integer cents, concurrent participant retries and ratings',async t=>{const {call,seat,read,db}=await setup(t);const {token}=await seat();const state=read();state.menu[0].price=30000;db.prepare('UPDATE state SET json=?').run(JSON.stringify(state));await call('order',{lines:[{id:'m0',qty:4,price:30000}],key:'meal'},token);assert.equal((await call('split',{people:4,key:'unauthorized'})).status,401);const split=(await call('split',{people:4,key:'split'},token)).data;assert.deepEqual(split.shares.map(s=>s.amount),[30000,30000,30000,30000]);assert.equal((await call('pay',{amount:120000,key:'bypass'},token)).status,409);const shareToken=split.shares[0].url.split('/').pop();const publicShare=(await call('share?token='+shareToken)).data;assert.equal(publicShare.amount,30000);assert.ok(!JSON.stringify(publicShare).includes(token));const b={token:shareToken,name:'Ahmed',key:'a'};const contenders=await Promise.all([call('share-pay',b),call('share-pay',{...b,key:'b'})]);assert.ok(contenders.every(r=>r.status===200));assert.equal(read().payments.length,1);assert.equal((await call('visit',undefined,token)).data.bill.due,90000);assert.equal((await call('rating',{shareToken,overall:5,food:5,service:4,speed:4})).status,200);assert.equal((await call('rating',{shareToken,overall:5})).status,200);assert.equal(read().ratings.length,1);assert.equal((await call('rating',{shareToken:split.shares[1].url.split('/').pop(),overall:5})).status,409);assert.equal((await call('share?token=bad')).status,404);});
test('floor reservation tags survive save, hidden tables cannot be reserved',async t=>{const {call,manager}=await setup(t);const floor=(await call('floor',undefined,manager)).data;floor.tables[1].features=['Window side','Quiet area'];floor.tables[1].reservable=false;assert.equal((await call('floor',{baseRevision:floor.revision,layout:floor,key:'feature'},manager)).status,200);const saved=(await call('public')).data.tables.find(x=>x.id==='t2');assert.deepEqual(saved.features,['Window side','Quiet area']);assert.equal(saved.available,false);assert.equal((await call('reserve',{tableId:'t2',party:4,name:'Guest',contact:'fictional',start:Date.now()+86400000,key:'hidden'})).status,400);});

test('scanning a table QR opens it automatically and never opens a second visit',async t=>{const {call,read}=await setup(t);const qr=(await call('public')).data.tables[0].qr;
 // No staff action needed: the scan itself opens the table.
 const opened=(await call('table-session',{qr})).data;assert.ok(opened.token);
 assert.equal((await call('visit',undefined,opened.token)).status,200);
 assert.equal(read().visits.filter(v=>v.status==='open').length,1);
 assert.equal(read().visits[0].auto,true);
 // Re-scanning joins the same visit instead of stacking another one.
 assert.equal((await call('table-session',{qr})).data.token,opened.token);
 assert.equal(read().visits.filter(v=>v.status==='open').length,1);
 assert.equal((await call('table-session',{qr:'missing'})).status,404);});

test('an auto-opened table can be released by staff only while it is still empty',async t=>{const {call,manager,read}=await setup(t);const qr=(await call('public')).data.tables[0].qr;
 const {token}=(await call('table-session',{qr})).data,id=read().visits[0].id;
 assert.equal((await call('undo-auto-open',{id})).status,401,'guests cannot release a table');
 assert.equal((await call('undo-auto-open',{id},manager)).status,200);
 assert.equal(read().visits.find(v=>v.id===id).status,'closed');
 // Once the guests have ordered, releasing is refused — the bill must be settled.
 const second=(await call('table-session',{qr})).data,secondId=read().visits.find(v=>v.status==='open').id;
 await call('order',{lines:[{id:'m0',qty:1,price:14500}],key:'ordered'},second.token);
 assert.equal((await call('undo-auto-open',{id:secondId},manager)).status,409);});

test('a table auto-closes only once paid, served and quiet — never before',async t=>{const {call,manager,kitchen,read,write}=await setup(t);const qr=(await call('public')).data.tables[0].qr;
 const {token}=(await call('table-session',{qr})).data;
 const o=(await call('order',{lines:[{id:'m0',qty:1,price:14500}],key:'o1'},token)).data;
 const openVisit=()=>read().visits.find(v=>v.status==='open');
 await call('pay',{amount:14500,key:'p1'},token);
 await call('staff',undefined,manager);
 assert.ok(openVisit(),'paid but still cooking must stay open');
 for(const [version,status]of ['preparing','ready','served'].entries())await call('transition',{id:o.id,version,status},kitchen);
 await call('staff',undefined,manager);
 assert.ok(openVisit(),'served and paid, but the grace period has not elapsed');
 // Wind the quiet clock back past the grace period.
 write(s=>{for(const x of s.orders)x.fulfilledAt=Date.now()-11*60000;for(const x of s.payments)x.at=Date.now()-11*60000;for(const v of s.visits)v.created=Date.now()-11*60000;});
 await call('staff',undefined,manager);
 assert.equal(openVisit(),undefined,'quiet, paid and served: the table closes itself');
 assert.equal((await call('seat',{tableId:'t1'},manager)).status,200,'and is immediately reusable');});
test('manager imports atomically and exports without secrets; kitchen and guest denied',async t=>{const {call,manager,kitchen,read}=await setup(t);const rows=[{name:'CSV soup',price_egp:25,stock:3}];assert.equal((await call('menu-preview',{rows})).status,401);assert.equal((await call('menu-import',{rows,key:'import'},kitchen)).status,401);assert.equal((await call('menu-import',{rows,key:'import'},manager)).status,200);assert.equal((await call('menu-import',{rows,key:'import'},manager)).status,200);assert.equal(read().menu.filter(m=>m.name==='CSV soup').length,1);assert.equal((await call('menu-import',{rows:[{name:'Good',price_egp:10},{name:'Bad',price_egp:0}],key:'bad'},manager)).status,400);assert.ok(!read().menu.some(m=>m.name==='Good'));assert.equal((await call('export?kind=reservations&format=json',undefined,kitchen)).status,401);assert.equal((await call('export?kind=menu&format=json',undefined,manager)).data.rows.filter(r=>!/^b\d+$/.test(r.id)).length,9,'the export covers this brand plus the imported row');});
test('Stripe checkout locks balance, validates signed callbacks, rejects mismatch, and retries once',async t=>{
 const keys=['STRIPE_SECRET_KEY','STRIPE_WEBHOOK_SECRET','PAYMENT_MODE'],previous=keys.map(k=>process.env[k]);process.env.STRIPE_SECRET_KEY='sk_test_fixture';process.env.STRIPE_WEBHOOK_SECRET='fixture-secret';process.env.PAYMENT_MODE='live';t.after(()=>keys.forEach((k,i)=>previous[i]===undefined?delete process.env[k]:process.env[k]=previous[i]));let requests=0;
 const {call,seat,order,read}=await setup(t,':memory:',{paymentFetch:async()=>{requests++;return {ok:true,json:async()=>({id:'cs_fixture',url:'https://checkout.stripe.com/c/fixture'})}}});const {token}=await seat();await order(token);const body={provider:'stripe',amount:5000,key:'checkout'};assert.equal((await call('checkout',body,token)).status,200);assert.equal((await call('checkout',body,token)).status,200);assert.equal(requests,1);assert.equal((await call('checkout',{...body,key:'other'},token)).status,409);assert.equal((await call('pay',{amount:5000,key:'fake'},token)).status,403);
 const make=amount=>({id:'evt_fixture',type:'checkout.session.completed',data:{object:{id:'cs_fixture',payment_status:'paid',amount_total:amount,currency:'egp'}}});const send=async event=>{const stamp=String(Math.floor(Date.now()/1000)),signature=createHmac('sha256','fixture-secret').update(stamp+'.'+JSON.stringify(event)).digest('hex');return call('webhooks/stripe',event,null,{'stripe-signature':'t='+stamp+',v1='+signature});};assert.equal((await call('webhooks/stripe',make(5000))).status,401);assert.equal((await send(make(6000))).status,409);assert.equal(read().payments.length,0);assert.equal((await send(make(5000))).status,200);assert.equal((await send(make(5000))).status,200);assert.equal(read().payments.length,1);assert.equal((await call('visit',undefined,token)).data.bill.due,9500);
});

async function setup(t,dbPath=':memory:',options={}){
 const app=createApp({dbPath,origin:'http://localhost:3000',managerPassword:'manager-test',kitchenPassword:'kitchen-test',...options});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port;
 t.after(async()=>{await new Promise(r=>app.server.close(r));app.db.close()});
 async function call(endpoint,body,credential,extra={}){const res=await fetch(base+'/api/'+endpoint,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(credential?.includes('session=')?{Cookie:credential}:credential?{Authorization:'Bearer '+credential}:{}),...extra},body:body?JSON.stringify(body):undefined});return {status:res.status,data:await res.json(),cookie:res.headers.get('set-cookie')?.split(';')[0]}}
 const manager=(await call('login',{role:'manager',password:'manager-test'})).cookie,kitchen=(await call('login',{role:'kitchen',password:'kitchen-test'})).cookie;
 const seat=async(tableId='t1')=>{const v=await call('seat',{tableId},manager);assert.equal(v.status,200);const t=(await call('public')).data.tables.find(t=>t.id===tableId);const joined=await call('join',{qr:t.qr,pin:v.data.pin});assert.equal(joined.status,200);return {v:v.data,token:joined.data.token}};
 const order=async(token,qty=1,key=crypto.randomUUID())=>call('order',{lines:[{id:'m0',qty,price:14500}],key},token);
 const write=fn=>{const state=app.read();fn(state);app.db.prepare('UPDATE state SET json=? WHERE id=1').run(JSON.stringify(state));};
 return {...app,call,manager,kitchen,seat,order,base,write};
}
test('staff role isolation and cross-origin protection',async t=>{const {call,kitchen}=await setup(t);assert.equal((await call('staff')).status,401);assert.equal((await call('seat',{tableId:'t1'},kitchen)).status,401);assert.equal((await call('login',{role:'manager',password:'wrong'})).status,401);assert.equal((await call('login',{role:'manager',password:'manager-test'},null,{Origin:'https://evil.example'})).status,403)});
test('QR identifies a table but never authorizes its bill',async t=>{const {call,seat}=await setup(t),{token}=await seat();const publicData=(await call('public')).data;assert.ok(publicData.tables[0].qr);assert.equal((await call('visit',undefined,publicData.tables[0].qr)).status,401);assert.equal((await call('join',{qr:publicData.tables[0].qr,pin:'000000'})).status,403);assert.equal((await call('visit',undefined,token)).status,200)});
test('walk-in -> order -> kitchen -> split payment -> close frees the table',async t=>{const {call,manager,kitchen,seat,order,read}=await setup(t),{v,token}=await seat();const o=(await order(token)).data;for(const [version,status]of ['preparing','ready','served'].entries())assert.equal((await call('transition',{id:o.id,version,status},kitchen)).status,200);assert.equal((await call('pay',{amount:5000,key:'part1'},token)).data.due,9500);assert.equal((await call('pay',{amount:9500,key:'part2'},token)).data.due,0);assert.equal((await call('close',{id:v.id},manager)).status,200);assert.equal(read().tables.find(t=>t.id==='t1').cleaning,false,'closing no longer parks the table in cleaning');assert.equal((await call('clean',{id:'t1'},manager)).status,200,'manual cleaning stays available');assert.equal((await call('seat',{tableId:'t1'},manager)).status,200,'and the table is reusable straight away')});
test('concurrent overlapping reservation contenders produce one hold',async t=>{const {call}=await setup(t);const body={tableId:'t2',party:4,name:'Test Guest',contact:'fictional',start:Date.now()+3600000};const r=await Promise.all([call('reserve',{...body,key:'a'}),call('reserve',{...body,key:'b'})]);assert.deepEqual(r.map(x=>x.status).sort(),[200,409])});
test('reservation capacity and buffer are enforced',async t=>{const {call}=await setup(t);const b={tableId:'t1',party:3,name:'Test',contact:'fictional',start:Date.now()+3600000,key:'a'};assert.equal((await call('reserve',b)).status,400);b.party=2;assert.equal((await call('reserve',b)).status,200);assert.equal((await call('reserve',{...b,start:b.start+95*60000,key:'b'})).status,409);assert.equal((await call('reserve',{...b,start:b.start+106*60000,key:'c'})).status,200)});
test('expired holds cannot take deposits and release their time',async t=>{const {call,db}=await setup(t);const b={tableId:'t1',party:2,name:'Test',contact:'fictional',start:Date.now()+3600000,key:'a'};const r=(await call('reserve',b)).data;const s=JSON.parse(db.prepare('SELECT json FROM state').get().json);s.reservations[0].expires=Date.now()-1;db.prepare('UPDATE state SET json=?').run(JSON.stringify(s));assert.equal((await call('deposit',{token:r.token,key:'pay'})).status,409);assert.equal((await call('reserve',{...b,key:'b'})).status,200)});
test('deposit idempotency, credit once, and unused credit refund',async t=>{const {call,manager,read}=await setup(t);const r=(await call('reserve',{tableId:'t1',party:2,name:'Test',contact:'fictional',start:Date.now()+1000,key:'r'})).data;const p={token:r.token,key:'deposit'};assert.equal((await call('deposit',p)).status,200);assert.equal((await call('deposit',p)).status,200);assert.equal(read().payments.length,1);const v=(await call('seat',{tableId:'t1',reservationId:r.id},manager)).data;assert.equal(v.bill.credit,20000);assert.equal((await call('seat',{tableId:'t1',reservationId:r.id},manager)).status,409);assert.equal((await call('close',{id:v.id},manager)).data.refund,20000);assert.equal(read().payments.filter(p=>p.kind==='test-refund').length,1)});
test('check-in rejects arrival outside the permitted window',async t=>{const {call,manager}=await setup(t);const r=(await call('reserve',{tableId:'t1',party:2,name:'Test',contact:'fictional',start:Date.now()+7200000,key:'r'})).data;await call('deposit',{token:r.token,key:'d'});assert.equal((await call('seat',{tableId:'t1',reservationId:r.id},manager)).status,400)});
test('guest tokens isolate visits',async t=>{const {call,seat,order}=await setup(t);const a=await seat('t1'),b=await seat('t2');await order(a.token);assert.equal((await call('visit',undefined,b.token)).data.orders.length,0);assert.equal((await call('visit',undefined,a.token)).data.orders.length,1)});
test('prices are rechecked and failed stock updates roll back entirely',async t=>{const {call,seat,read}=await setup(t),{token}=await seat();const stock=read().menu[0].stock;assert.equal((await call('order',{lines:[{id:'m0',qty:1,price:1}],key:'bad'},token)).status,409);assert.equal((await call('order',{lines:[{id:'m0',qty:1,price:14500},{id:'m1',qty:50,price:9500}],key:'stock'},token)).status,409);assert.equal(read().menu[0].stock,stock);assert.equal(read().orders.length,0)});
test('duplicate order keys return the same order and reject altered data',async t=>{const {order,seat,read}=await setup(t),{token}=await seat();const a=await order(token,1,'same'),b=await order(token,1,'same');assert.equal(a.data.id,b.data.id);assert.equal(read().orders.length,1);assert.equal((await order(token,2,'same')).status,409)});
test('concurrent payments never overpay, and a settled guest can still order more',async t=>{const {call,seat,order,read}=await setup(t),{token}=await seat();await order(token);
 const r=await Promise.all([call('pay',{amount:10000,key:'a'},token),call('pay',{amount:10000,key:'b'},token)]);
 assert.deepEqual(r.map(x=>x.status).sort(),[200,409]);
 assert.equal(read().payments.reduce((n,p)=>n+p.amount,0),10000,'never overpays');
 // Paying part of the bill must not end the meal: dessert and drinks still work.
 assert.equal((await order(token)).status,200);});
test('payment retry remains idempotent after balance changes',async t=>{const {call,seat,order,read}=await setup(t),{token}=await seat();await order(token);const b={amount:14500,key:'p'};assert.equal((await call('pay',b,token)).status,200);assert.equal((await call('pay',b,token)).status,200);assert.equal(read().payments.length,1)});
test('a bill request is deduplicated and never freezes the menu',async t=>{const {call,seat,order,read}=await setup(t),{token}=await seat();
 await call('request',{type:'bill',key:'a'},token);await call('request',{type:'bill',key:'b'},token);
 assert.equal(read().requests.length,1,'deduplicated');
 assert.equal((await order(token)).status,200,'asking for the bill does not stop ordering');});

test('ordering pauses only while a payment is genuinely in flight',async t=>{
 const keys=['STRIPE_SECRET_KEY','STRIPE_WEBHOOK_SECRET','PAYMENT_MODE'],previous=keys.map(k=>process.env[k]);
 process.env.STRIPE_SECRET_KEY='sk_test_fixture';process.env.STRIPE_WEBHOOK_SECRET='fixture-secret';process.env.PAYMENT_MODE='live';
 t.after(()=>keys.forEach((k,i)=>previous[i]===undefined?delete process.env[k]:process.env[k]=previous[i]));
 const {call,seat,order}=await setup(t,':memory:',{paymentFetch:async()=>({ok:true,json:async()=>({id:'cs_fixture',url:'https://checkout.stripe.com/c/fixture'})})});
 const {token}=await seat();await order(token);
 assert.equal((await call('checkout',{provider:'stripe',amount:5000,key:'c1'},token)).status,200);
 assert.equal((await order(token)).status,409,'a pending provider checkout pauses ordering');
 const event={id:'evt_fixture',type:'checkout.session.completed',data:{object:{id:'cs_fixture',payment_status:'paid',amount_total:5000,currency:'egp'}}};
 const stamp=String(Math.floor(Date.now()/1000)),signature=createHmac('sha256','fixture-secret').update(stamp+'.'+JSON.stringify(event)).digest('hex');
 await call('webhooks/stripe',event,null,{'stripe-signature':'t='+stamp+',v1='+signature});
 assert.equal((await order(token)).status,200,'and resumes by itself once the webhook lands');});
test('stale kitchen transitions rejected; payment does not fulfill food',async t=>{const {call,manager,kitchen,seat,order}=await setup(t),{token,v}=await seat();const o=(await order(token)).data;await call('transition',{id:o.id,version:0,status:'preparing'},kitchen);assert.equal((await call('transition',{id:o.id,version:0,status:'ready'},kitchen)).status,409);await call('pay',{amount:14500,key:'p'},token);assert.equal((await call('close',{id:v.id},manager)).status,409)});
test('cancellation restores stock only once',async t=>{const {call,manager,seat,order,read}=await setup(t),{token}=await seat();const o=(await order(token)).data;assert.equal(read().menu[0].stock,17);assert.equal((await call('transition',{id:o.id,version:0,status:'cancelled'},manager)).status,200);assert.equal((await call('transition',{id:o.id,version:1,status:'cancelled'},manager)).status,400);assert.equal(read().menu[0].stock,18)});
test('floor stale saves and archiving occupied tables rejected; QR stable',async t=>{const {call,manager,seat,read}=await setup(t);const table=read().tables[0];const b={...table,label:'Window 1',x:25};assert.equal((await call('table',b,manager)).status,200);assert.equal(read().tables[0].qr,table.qr);assert.equal((await call('table',b,manager)).status,409);await seat();assert.equal((await call('table',{...b,version:1,active:false},manager)).status,409)});
test('pickup and delivery use shared kitchen with correct fees and transitions',async t=>{const {call,kitchen,order}=await setup(t);for(const type of ['pickup','delivery']){const r=await call('offsite',{type,name:'Test',contact:'fictional',address:'Demo address',key:type});const token=r.data.token;assert.equal((await call('visit',undefined,token)).data.bill.fee,type==='delivery'?3500:0);const o=(await order(token)).data;for(const [version,status]of ['preparing','ready',...(type==='delivery'?['out_for_delivery','delivered']:['picked_up'])].entries())assert.equal((await call('transition',{id:o.id,version,status},kitchen)).status,200)}});
test('menu rules respect budget, vegetarian filter, allergens and quantities',async t=>{const {call,read}=await setup(t);const r=(await call('recommend',{budget:40000,party:2,vegetarian:true,exclude:['milk']})).data;assert.equal(r.mode,'Demo rules');assert.ok(r.lines.length);let total=0;for(const l of r.lines){const m=read().menu.find(m=>m.id===l.id);assert.ok(m.vegetarian);assert.ok(!m.allergens.includes('milk'));total+=m.price*l.qty}assert.ok(total<=40000);assert.equal((await call('recommend',{budget:1,party:2})).data.lines.length,0)});
test('SQLite persists restaurant data and QR identities after reopening',async t=>{const dir=mkdtempSync(path.join(tmpdir(),'resuto-test-')),dbPath=path.join(dir,'state.sqlite');const a=createApp({dbPath,managerPassword:'a',kitchenPassword:'b'});const qr=a.read().tables[0].qr;a.db.close();const b=createApp({dbPath});assert.equal(b.read().tables[0].qr,qr);b.db.close();rmSync(dir,{recursive:true,force:true})});
test('QR endpoint is real SVG and public data contains no credentials',async t=>{const {call,base}=await setup(t);const d=(await call('public')).data;assert.equal(d.credentials,undefined);assert.equal(d.visits,undefined);const qr=await fetch(base+'/qr/'+d.tables[0].qr);assert.equal(qr.headers.get('content-type'),'image/svg+xml');assert.match(await qr.text(),/<svg/)});
test('menu creation, category edits and stock edits cannot overwrite concurrent sales',async t=>{const {call,manager,seat,order,read}=await setup(t);const m=(await call('menu',{add:true,name:'Demo salad',category:'Specials',station:'Cold kitchen',allergens:[],vegetarian:true,price:15000,stock:5,available:true},manager)).data;assert.equal(m.name,'Demo salad');const original={...read().menu[0]},{token}=await seat();await order(token);assert.equal((await call('menu',original,manager)).status,409);assert.equal(read().menu[0].stock,17);assert.equal((await call('menu',{...m,category:'Starters'},manager)).data.category,'Starters')});
test('background uploads reject unsafe formats and preserve settings',async t=>{const {call,manager,read}=await setup(t);assert.equal((await call('background',{image:'data:image/svg+xml;base64,PHN2Zz4='},manager)).status,400);const image='data:image/png;base64,iVBORw0KGgo=';assert.equal((await call('background',{image},manager)).status,200);await call('settings',{...read().settings,name:'Demo Restaurant'},manager);assert.equal(read().settings.background,image);assert.equal((await call('background',{image:null},manager)).status,200)});
test('concurrent orders cannot oversell remaining portions',async t=>{const {call,manager,seat,order,read}=await setup(t);await call('menu',{...read().menu[0],stock:1},manager);const {token}=await seat();const r=await Promise.all([order(token,1,'a'),order(token,1,'b')]);assert.deepEqual(r.map(x=>x.status).sort(),[200,409]);assert.equal(read().menu[0].stock,0)});
test('floor migration retains table identities and runs only once',async t=>{const {read}=await setup(t);const s=read();delete s.floor;const ids=s.tables.map(t=>[t.id,t.qr]);assert.equal(migrateFloor(s),true);const first=JSON.stringify(s);assert.equal(migrateFloor(s),false);assert.equal(JSON.stringify(s),first);assert.deepEqual(s.tables.map(t=>[t.id,t.qr]),ids);assert.equal(s.tables[0].cx,s.tables[0].x*12)});
test('floor read/write require manager while public geometry filters private table notes',async t=>{const {call,manager,kitchen}=await setup(t);assert.equal((await call('floor')).status,401);assert.equal((await call('floor',undefined,kitchen)).status,401);const f=(await call('floor',undefined,manager)).data;f.tables[0].internalNotes='VIP preference kept private';assert.equal((await call('floor',{baseRevision:f.revision,layout:f,key:'a'},kitchen)).status,401);const saved=(await call('floor',{baseRevision:f.revision,layout:f,key:'manager-save'},manager)).data;assert.equal(saved.tables[0].internalNotes,'VIP preference kept private');const p=(await call('public')).data.floor;assert.equal(p.tables[0].internalNotes,undefined);assert.equal(JSON.stringify((await call('public')).data).includes('VIP preference kept private'),false);assert.equal(p.tables[0].qr,undefined);assert.equal(p.tables[0].pin,undefined)});
test('floor commit preserves occupancy, cleaning and QR while replacing only geometry',async t=>{const {call,manager,seat,read}=await setup(t);const f=(await call('floor',undefined,manager)).data;const old=read().tables[0];await seat();f.tables[0].cx=300;f.tables[0].label='Window seat';f.tables[0].cleaning=false;f.tables[0].qr='replace-me';const r=await call('floor',{baseRevision:f.revision,layout:f,key:'save'},manager);assert.equal(r.status,200);assert.equal(read().tables[0].qr,old.qr);assert.equal(read().tables[0].cx,300);assert.equal(read().visits[0].status,'open');assert.equal((await call('seat',{tableId:'t1'},manager)).status,409)});
test('floor retries create tables once with server-issued QR and identity',async t=>{const {call,manager,read}=await setup(t);const f=(await call('floor',undefined,manager)).data;f.tables.push({...f.tables[0],id:'new-test',label:'T7',cx:400,cy:400});const b={baseRevision:f.revision,layout:f,key:'save'};const a=await call('floor',b,manager),retry=await call('floor',b,manager);assert.equal(a.status,200);assert.deepEqual(a.data,retry.data);assert.equal(read().tables.length,7);assert.notEqual(read().tables[6].id,'new-test');assert.ok(read().tables[6].qr);assert.equal((await call('floor',{...b,layout:{...f,revision:999}},manager)).status,409)});
test('concurrent layout saves conflict; legacy writes also advance layout revision',async t=>{const {call,manager,read}=await setup(t);const f=(await call('floor',undefined,manager)).data;const r=await Promise.all([call('floor',{baseRevision:f.revision,layout:f,key:'a'},manager),call('floor',{baseRevision:f.revision,layout:f,key:'b'},manager)]);assert.deepEqual(r.map(r=>r.status).sort(),[200,409]);const latest=(await call('floor',undefined,manager)).data;await call('table',{...read().tables[0],x:30},manager);assert.equal((await call('floor',{baseRevision:latest.revision,layout:latest,key:'c'},manager)).status,409);const next=(await call('floor',undefined,manager)).data;await call('background',{image:null},manager);assert.equal((await call('floor',{baseRevision:next.revision,layout:next,key:'d'},manager)).status,409)});
test('invalid rotated geometry rolls back entire save',async t=>{const {call,manager,read}=await setup(t);const original=JSON.stringify(read().tables),f=(await call('floor',undefined,manager)).data;f.tables[0].label='Changed';f.tables[1].cx=20;f.tables[1].rotation=45;const r=await call('floor',{baseRevision:f.revision,layout:f,key:'bad'},manager);assert.equal(r.status,400);assert.equal(JSON.stringify(read().tables),original);assert.equal(read().floor.revision,f.revision)});
test('floor deletion archives free tables and blocks protected tables',async t=>{const {call,manager,seat,read}=await setup(t);let f=(await call('floor',undefined,manager)).data;f.tables=f.tables.filter(t=>t.id!=='t6');assert.equal((await call('floor',{baseRevision:f.revision,layout:f,key:'free'},manager)).status,200);assert.equal(read().tables.find(t=>t.id==='t6').active,false);await seat();f=(await call('floor',undefined,manager)).data;f.tables=f.tables.filter(t=>t.id!=='t1');assert.equal((await call('floor',{baseRevision:f.revision,layout:f,key:'occupied'},manager)).status,409);assert.equal(read().tables[0].active,true)});
test('layout objects and uploaded background persist and reject untrusted types',async t=>{const {call,manager}=await setup(t);const f=(await call('floor',undefined,manager)).data;f.objects.push({id:'new-label',type:'text',label:'<script>test</script>',x:500,y:500,width:180,height:40,rotation:0});f.background.opacity=.25;assert.equal((await call('floor',{baseRevision:f.revision,layout:f,key:'valid'},manager)).status,200);const saved=(await call('floor',undefined,manager)).data;assert.equal(saved.background.opacity,.25);saved.objects[0].type='script';assert.equal((await call('floor',{baseRevision:saved.revision,layout:saved,key:'bad'},manager)).status,400)});
