import test from 'node:test';
import assert from 'node:assert/strict';
import {createApp} from '../server.js';
import {demoFloor} from '../public/floor-model.js';
import {recommendTables} from '../restaurant-experience.js';

test('sales inquiries persist privately, reject malformed data and deduplicate retries',async t=>{const {call,manager}=await setup(t);const b={restaurant:'Example',email:'demo@example.test',branches:3,requirements:'A three-branch trial',key:'lead'};assert.equal((await call('sales-inquiry',{...b,email:'invalid'})).status,400);assert.equal((await call('sales-inquiry',b)).status,200);assert.equal((await call('sales-inquiry',b)).status,200);assert.equal((await call('setup',null,manager)).data.salesInquiries.length,1);assert.ok(!JSON.stringify((await call('public')).data).includes('demo@example.test'));});

test('Gemini table output is validated against metadata, actual IDs and party size',async t=>{const original=globalThis.fetch,key=process.env.GEMINI_API_KEY;process.env.GEMINI_API_KEY='test-key';t.after(()=>{globalThis.fetch=original;if(key===undefined)delete process.env.GEMINI_API_KEY;else process.env.GEMINI_API_KEY=key;});const s={branches:[{id:'main',active:true,reservations:true}],settings:{duration:90,buffer:15},visits:[],reservations:[],tables:[{id:'quiet',label:'T9',active:true,capacity:4,features:['Quiet area','Far from entrance'],zone:'Main'},{id:'small',label:'T1',active:true,capacity:2,features:['Quiet area','Far from entrance'],zone:'Main'}]};globalThis.fetch=async()=>({ok:true,json:async()=>({candidates:[{content:{parts:[{text:JSON.stringify({tableIds:['invented','small','quiet']})}]}}]})});const result=await recommendTables(s,{start:Date.now()+86400000,party:4,message:'عايز مكان هادي بعيد عن الباب'});assert.deepEqual(result.tableIds,['quiet']);assert.equal(result.mode,'gemini');const six=await recommendTables(s,{start:Date.now()+86400000,party:4,message:'We are 6 people'});assert.deepEqual(six.tableIds,[]);});
async function setup(t){const app=createApp({dbPath:':memory:',origin:'http://localhost:3000',managerPassword:'test-manager',kitchenPassword:'test-kitchen'});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port;t.after(async()=>{await new Promise(r=>app.server.close(r));app.db.close();});async function call(route,body,cookie){const r=await fetch(base+'/api/'+route,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}const manager=(await call('login',{role:'manager',password:'test-manager'})).cookie;return {app,call,manager};}
test('setup is manager-only, revision protected, validates links and retains operational records',async t=>{const {call,manager,app}=await setup(t);assert.equal((await call('setup')).status,401);const before=app.read(),draft=(await call('setup',null,manager)).data;const body={baseRevision:draft.revision,step:2,plan:'growth',mode:'native',profile:{name:'Resuto Demo Restaurant',type:'Restaurant',cuisine:'Egyptian',country:'Egypt',contact:'demo',language:'ar',currency:'EGP',timezone:'Africa/Cairo'},branch:{...draft.branch,name:'Downtown Branch',address:'Demo',phone:'',hours:'',mapsUrl:'',dineIn:true,reservations:true}};assert.equal((await call('setup',body)).status,401);assert.equal((await call('setup',body,manager)).status,200);assert.equal((await call('setup',body,manager)).status,409);assert.deepEqual(app.read().tables,before.tables);assert.equal((await call('setup',{...body,baseRevision:1,branch:{...body.branch,mapsUrl:'javascript:alert(1)'}},manager)).status,400);assert.equal(app.read().setup.revision,1);});
test('12-table template persists metadata, availability excludes reservations and AI only returns actual matching tables',async t=>{const {call,manager,app}=await setup(t);const current=(await call('floor',null,manager)).data,draft=demoFloor();draft.tables[5].minimumSpend=50000;draft.tables[5].locked=true;draft.zones[0].hidden=true;const save=await call('floor',{baseRevision:current.revision,layout:draft,key:'template'},manager);assert.equal(save.status,200);assert.equal(save.data.tables.length,12);const window=save.data.tables.find(t=>t.label==='T6');assert.equal(window.minimumSpend,50000);assert.equal(window.locked,true);assert.equal(save.data.zones[0].hidden,true);const q={start:Date.now()+86400000,party:4,branchId:'main'};const rec=await call('table-recommend',{...q,message:'عايز مكان هادي بعيد عن الباب'});assert.deepEqual(rec.data.tables.map(t=>t.label),['T9']);assert.equal((await call('table-recommend',{...q,party:50,message:'window'})).status,400);const r=(await call('reserve',{...q,tableId:window.id,name:'Test',contact:'test',key:'book'})).data;assert.equal((await call('availability?'+new URLSearchParams(q))).data.tableIds.includes(window.id),false);const b={token:r.token,key:'deposit'};assert.equal((await call('deposit',b)).status,200);assert.equal((await call('deposit',b)).status,200);assert.equal(app.read().payments.length,1);assert.equal((await call('reservation?token='+r.token)).data.table.label,'T6');assert.equal((await call('reservation?token=invalid')).status,404);assert.equal((await call('reservation-change',{...q,start:q.start+86400000,token:r.token,tableId:window.id,action:'modify',key:'move'})).status,200);assert.equal((await call('reservation-change',{token:r.token,action:'cancel',key:'cancel'})).status,200);assert.equal((await call('reservation-change',{token:r.token,action:'cancel',key:'cancel'})).status,200);assert.equal(app.read().reservations[0].status,'cancelled');});
test('invalid premium metadata and geometry roll back together; pricing is honest about unavailable billing',async t=>{const {call,manager,app}=await setup(t);const before=app.read(),f=(await call('floor',null,manager)).data;f.tables[0].minimumSpend=-1;assert.equal((await call('floor',{baseRevision:f.revision,layout:f,key:'bad'},manager)).status,400);assert.deepEqual(app.read().tables,before.tables);const plans=(await call('plans')).data;assert.deepEqual(plans.plans.map(p=>p.monthly),[799,1499,2999,null]);assert.equal(plans.billingEnabled,false);});
