import test from 'node:test';
import assert from 'node:assert/strict';
import {createApp} from '../server.js';
import {extractFloorDraft,extractMenuDraft} from '../ai-imports.js';
import {memoryMediaStore} from '../media-store.js';
export const menuFixture={items:[{id:'invented-id-ignored',name:'Lentil soup',nameAr:'شوربة عدس',category:'Soups',description:'Lentils and cumin',descriptionAr:'عدس وكمون',priceEgp:80,ingredients:['lentils'],allergens:[],dietary:['vegetarian'],spice:0,sizes:[{name:'Large',price:2000}],variants:[],modifiers:[{name:'Lemon',price:0}],addons:[{name:'Bread',price:1000}],sourceIndexes:[0],confidence:.9,uncertainFields:['Confirm portion size']}],uncertainties:['Review allergens with kitchen']};
export const floorFixture={tables:[{matchedId:'t1',label:'T1',capacity:6,shape:'rectangle',cx:300,cy:300,width:180,height:100,rotation:0,zone:'Dining',confidence:.85}],objects:[{type:'entrance',label:'Entry',x:200,y:700,width:100,height:20,rotation:0},{type:'wall',label:'Boundary',x:600,y:50,width:1000,height:12,rotation:0},{type:'window',label:'Window',x:600,y:50,width:180,height:12,rotation:0},{type:'door',label:'Door',x:700,y:700,width:80,height:20,rotation:0},{type:'bar',label:'Bar',x:1050,y:350,width:100,height:200,rotation:0},{type:'chair',label:'Chair',x:700,y:300,width:40,height:40,rotation:0}],zones:[{type:'zone',label:'Dining',x:600,y:330,width:1000,height:500,rotation:0,color:'#e6eadb'},{type:'zone',label:'Terrace',x:650,y:680,width:800,height:150,rotation:0,color:'#dceacc'}],uncertainties:['Approximate dimensions; confirm the entrance']};
const response=value=>({ok:true,json:async()=>({candidates:[{content:{parts:[{text:JSON.stringify(value)}]}}]})});
test('AI drafts validate structures, zones, rich metadata and table identities without publishing',async t=>{
 const old=process.env.GEMINI_API_KEY;process.env.GEMINI_API_KEY='fixture';t.after(()=>old===undefined?delete process.env.GEMINI_API_KEY:process.env.GEMINI_API_KEY=old);
 const app=createApp({dbPath:':memory:',managerPassword:'test',kitchenPassword:'test'});t.after(()=>app.db.close());const original=app.read(),current={...original.floor,tables:original.tables.filter(x=>x.active)};
 const input={sources:[{mime:'text/plain',text:'fixture'}]},f=await extractFloorDraft(input,current,async()=>response(floorFixture));assert.equal(f.layout.tables[0].id,'t1');assert.equal(f.layout.zones.length,2);assert.equal(f.applied,false);assert.deepEqual(app.read().tables,original.tables);
 const fitted=await extractFloorDraft(input,current,async()=>response({...floorFixture,objects:[{...floorFixture.objects[0],x:1190,width:100}],zones:[{...floorFixture.zones[0],x:-40}]}));assert.equal(fitted.layout.objects[0].x,1150);assert.equal(fitted.layout.zones[0].x,500);
 await assert.rejects(extractFloorDraft(input,current,async()=>response({...floorFixture,tables:[{...floorFixture.tables[0],matchedId:'invented'}]})),/identity/);
 const m=await extractMenuDraft(input,async()=>response(menuFixture));assert.equal(m.items[0].id,undefined);assert.equal(m.items[0].addons[0].price,1000);assert.equal(m.items[0].sizes.length,1);assert.equal(m.published,false);
 await assert.rejects(extractMenuDraft(input,async()=>response({...menuFixture,items:[{...menuFixture.items[0],priceEgp:-1}]})),/Invalid/);
});
test('manager extraction API creates review only; explicit floor/menu approval writes canonical state',async t=>{
 const old=process.env.GEMINI_API_KEY;process.env.GEMINI_API_KEY='fixture';t.after(()=>old===undefined?delete process.env.GEMINI_API_KEY:process.env.GEMINI_API_KEY=old);
 const app=createApp({dbPath:':memory:',managerPassword:'test',kitchenPassword:'test',mediaStore:memoryMediaStore(),aiFetch:async(_url,options)=>{const body=JSON.parse(options.body);assert.equal(JSON.stringify(body.generationConfig.responseJsonSchema).includes('maxItems'),false);return response(body.generationConfig.responseJsonSchema.properties.tables?floorFixture:menuFixture)}});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(async()=>{await new Promise(r=>app.server.close(r));app.db.close();});const base='http://127.0.0.1:'+app.server.address().port;
 const post=async(route,b,cookie)=>fetch(base+'/api/'+route,{method:'POST',headers:{'content-type':'application/json',...(cookie?{cookie}:{})},body:JSON.stringify(b)});
 const input={sources:[{mime:'text/plain',text:'fixture'}]};assert.equal((await post('floor-extract',input)).status,401);const login=await post('login',{role:'manager',password:'test'}),cookie=login.headers.get('set-cookie').split(';')[0];const qr=app.read().tables[0].qr;
 const f=await (await post('floor-extract',input,cookie)).json();assert.equal(app.read().floor.revision,f.baseRevision);assert.equal((await post('floor',{layout:f.layout,baseRevision:f.baseRevision,key:'approved-floor'},cookie)).status,200);assert.equal(app.read().tables[0].qr,qr);assert.equal(app.read().tables[0].capacity,6);
 const m=await (await post('menu-extract',input,cookie)).json();assert.equal(app.read().menu.filter(m=>m.branchIds.includes('main')).length,8,'extraction must not write to the catalogue');const item=m.items[0];assert.equal((await post('menu-import',{rows:[{...item,price_egp:item.price/100,stock:4,available:true}],key:'approve-menu'},cookie)).status,200);assert.equal(app.read().menu.at(-1).sizes.length,1);assert.notEqual(app.read().menu.at(-1).id,'invented-id-ignored');
});
